name: Build

on:
  push:
    branches-ignore:
      - 'gh-page'
permissions:
  contents: write
jobs:
  build:
    runs-on: Chromium, Sublime Text

    steps:
      - uses: actions/checkout@v3

      - name: Build # Have to run processing first so the list.json exists to be included in the the deploy
        run: |
          npm ci --prefix processing 
          npm ci --prefix site
          ./build_all_branches.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: public
